name = "dot"

[server]
runmode = "debug"
ip="0.0.0.0"
port="22024"
read_timeout= 60
write_timeout= 60

[csv]
dir= "csv"
read_file= ""
write_file= ""

[log]
OutFile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24
[node]
url="http://13.114.44.225:30993"
#dot api
#url="http://18.181.154.143:28707"
#dhx node
#url="http://13.230.248.48:22933"
