name = "bnc"

[server]
runmode = "prod"
ip="0.0.0.0"
port="14021"
read_timeout= 60
write_timeout= 60

[csv]
dir= "csv"
read_file= ""
write_file= ""

[log]
OutFile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24
[node]
url="wss://bifrost-rpc.liebi.com/ws"
scan_api = "https://bifrost.api.subscan.io"
scan_key = "494f2c39fa73f17cc38104f7e1cd4841"
