appname = "bosDataServer"

[server]
runmode = "debug"
ip="0.0.0.0"
port="22001"
read_timeout= 60
write_timeout= 60

[Sync]
name = "bos"
enablesync = true
enablegoroutine = true
enablemempool = false
fullbackup = true #交易全量保存数据库
initheight = 123080650
#延迟高度扫块
delaycount = 10
#启用回滚高度
enablerollback = true
#回滚高度
rollheight = 123093035
#确认数
confirmations = 12

[nodes.bos]
url="https://bos.eosn.io"
#url="https://api.bossweden.org"
#url="https://api.bosexplorer.io"
#rpc_key = "rylink"
#rpc_secret = "4CpmLnbOiaTbD20gPdsRYY6WiMFDyF8N8QzGGYrAfIw="

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "user"
password= "123456"
mode= "release"

[databases.sync]
name= "bossync"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "user"
password= "123456"
mode= "release"


[push]
enable = true
type = "rabbitmq" #rabbitmq/http
agent = false
url = "http://127.0.0.1:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="amqp://rylink:rylink2020@172.17.2.65"
reconns=30
publishers=["bos"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "info" #debug info warn error panic
max_age= 24
rotation_time= 24