appname = "zecsync"

[Sync]
name = "zec"
enablesync = true
enablegoroutine = false
enablemempool = true
fullbackup = true
epochcount = 100
epochtime  = 60
initheight = 482961 #920192
enablerollback = false
rollheight = 10000
confirmations = 6
intervaltime = 20

[nodes.zec]
url = "http://zec.rylink.io:30232"
rpc_key = "ycashuser"
rpc_secret = "6fecfcc686045379e467fce52692fd81"

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "user"
password= "123456"
mode= "release"

[databases.sync]
name= "zecsync"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "user"
password= "123456"
mode= "release"

[server]
runmode = "debug"
ip="0.0.0.0"
port="18895"
read_timeout= 60
write_timeout= 60


[push]
enable = true
type = "rabbitmq" #rabbitmq/http
agent = false
url = "http://127.0.0.1:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="amqp://rylink:rylink2020@172.17.2.65"
reconns=30
publishers=["cds"]

[log]
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
max_age= 24
rotation_time= 24

