appname = "dhxsync"

[server]
runmode = "debug"
ip="0.0.0.0"
port="13000"
read_timeout= 60
write_timeout= 60

[Sync]
name = "dhx"
enablesync = true
enablemultiscan = 10
enablegoroutine = true
enablemempool = false  #
fullbackup = true #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 2
epochtime  = 60
initheight = 2907250
enablerollback = false
rollheight = 217600
confirmations = 12
intervaltime = 0

[nodes.dhx]
node ="http://54.64.160.150:22933"
url ="http://54.64.160.150:8585"

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"

[databases.sync]
name= "dhxsync"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"


[push]
enable = false
type = "rabbitmq" #rabbitmq/http
agent = false
url = "http://127.0.0.1:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="amqp://rylink:rylink2020@172.17.2.65"
reconns=30
publishers=["dhx"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"  #text,json
mode= "dev" #dev pro
level= "debug" #debug info warn error panic
