run_model: "debug"

system_model: cold #冷热系统切换 cold hot
#system_model: hot #冷热系统切换 cold cold

http:
  port: 9987
  read_timeout: 120
  write_timeout: 120

log:
  log_path: "./tmp"
  log_name: "ltcserver.log"
  log_level: "debug"

ltc:
 addr_path: "./pem/ltc/file"  #地址读取目录
 create_addr_path: "./pem/ltc/create"  #地址生成目录
 default_fee: 100000 #0.001 默认手续费
 max_fee: 10000000 #0.1 默认最高手续费
 min_fee: 1000 #0.0001 默认最低手续费
 push_servers:
 - "http://47.244.140.180:9999/api/v1/ltc/send" #广播URL
 servers:
 - "http://47.244.140.180:9999/" #暂时无用，无需通过rpc客户端

#cron表达式
cron:
  loadkeyjob: "@every 5s"

