name = "btc"

[server]
runmode = "debug"
ip="0.0.0.0"
port="10032"
read_timeout= 60
write_timeout= 60

[Sync]
name = "btc"
enablesync = false
enable_usdt_scan = true
enablegoroutine = false
enablemultiscan = 1
enablemempool = true  #
fullbackup = false #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
initheight = 733362 #初始扫块高度
enablerollback = true
rollheight = 730520
confirmations = 6
address_discover = 10 #新增地址发现:0 不开启, >0 查询间隔秒数
contract_discover = 10 #新增合约发现:0 不开启, >0 查询间隔秒数

[nodes.btc]
url = "http://rylink:4CpmLnbOiaTbD20gPdsRYY6WiMFDyF8N8QzGGYrAfIw=@192.169.1.173:31821"
usdt = "http://user:709394@192.170.1.236:9990"
#url = "http://rylink:4CpmLnbOiaTbD20gPdsRYY6WiMFDyF8N8QzGGYrAfIw=@13.230.58.120:31821"

[databases.user]
name= "addrmanagement"
type = "mysql"
url = "test-middle-server-instance-1.camzhqc6mnkb.ap-northeast-1.rds.amazonaws.com:3306"
user=  "hoocustody"
password = "Eb!ZXrNt!!x5xru0"

[databases.sync]
name = "btcsync"
type = "mysql"
url = "test-middle-server-instance-1.camzhqc6mnkb.ap-northeast-1.rds.amazonaws.com:3306"
user = "hoocustody"
password = "Eb!ZXrNt!!x5xru0"

[mq]
hostport = "b-30ba08b2-dbea-4e1a-a282-b4569cb9896f.mq.ap-northeast-1.amazonaws.com:5671"
username = "blockchain_coin-MQ"
password  = "draXv3HB4dKqmDjANU"

[push]
enable = false
type = "http" #rabbitmq/http
agent = true
url = "http://127.0.0.1:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="amqp://rylink:rylink2020@172.17.2.65"
reconns=30
publishers=["moac"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "info" #debug info warn error panic
max_age= 24
rotation_time= 24