appname = "fissync"
mode = "prod"
[server]
runmode = "debug"
ip="0.0.0.0"
port="15005"
read_timeout= 60
write_timeout= 60

[Sync]
name = "fis"
enablesync = true
enablegoroutine = true
enablemempool = false  #
fullbackup = false #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 2
epochtime  = 60
initheight = 4818891
enablerollback = false
rollheight = 4818891
confirmations = 12
intervaltime = 20

[nodes.fis]
node ="http://fis.rylink.io:31833"
url ="http://127.0.0.1:31880"

[databases.user]
name= "6kDzq6McR2q5Id4Br0Q="
type= "mysql"
url= "70XjuL0YW323J9ZJolwfwjhCQjaocNirV7yzlGPOUV3HnDBHQuwxNomkDv/vvg5hKZijxuEaWis1/3JhXVW2lGRSxXAnWV3/tIaaR6Ou5A=="
user= "70XjuJEOTHmoLdAB"
password= "32in/6k/X2K8fNwO+UIG3Q=="
mode= "release"

[databases.sync]
name= "7U3kqrcTSg=="
type= "mysql"
url= "70XjuL0YW323J9ZJolwfwjhCQjaocNirV7yzlGPOUV3HnDBHQuwxNomkDv/vvg5hKZijxuEaWis1/3JhXVW2lGRSxXAnWV3/tIaaR6Ou5A=="
user= "70XjuJEOTHmoLdAB"
password= "32in/6k/X2K8fNwO+UIG3Q=="
mode= "release"


[push]
enable = true
type = "http" #rabbitmq/http
agent = true
url = "http://192.169.2.157:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="6knmqfRSBnmnKNoKqgoC284lriwMppBmnYedYdOK9LFRdab8+F9Fo7uT1PsVaW/XnGhtL5xTqCA="
reconns=30
publishers=["dot"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
mode= "dev" #dev pro
level= "info" #debug info warn error panic
