name = "star"

[server]
runmode = "debug"
ip="0.0.0.0"
port="18083"
read_timeout= 60
write_timeout= 60

[csv]
dir= "csv"
read_file= ""
write_file= ""

[log]
OutFile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24
[node]
url = "http://52.195.10.13:21234/rpc/v0?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.01VP0lrC2n7Ci0y5GoIR1IK5WwvKRrZMLidhHTmRo_g"
#url = "http://fil.rylink.io:1234/rpc/v0?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiXX0.qAJaIRSZumi91_mHXCqLr8oHgeD6auFy5CvRD98Aj7w"
#rylink:4CpmLnbOiaTbD20gPdsRYY6WiMFDyF8N8QzGGYrAfIw=@rpc_key = "rylink"
#rpc_secret = "4CpmLnbOiaTbD20gPdsRYY6WiMFDyF8N8QzGGYrAfIw="