// Copyright (c) 2018-2021 The MobileCoin Foundation

// MUST BE KEPT IN SYNC WITH RUST CODE!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: watcher.proto

package mobilecoindapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

/// The result code indicating whether the timestamp was found, can be tried again later, or will
/// never be found with the current configuration of the service offering timestamps via the watcher.
type TimestampResultCode int32

const (
	/// The default value for fixed32 is intentionally unused to avoid omitting this field.
	TimestampResultCode_UnusedField TimestampResultCode = 0
	/// The timestamp was found for at least one watched consensus validator.
	TimestampResultCode_TimestampFound TimestampResultCode = 1
	/// The timestamp was not found, but the watcher sync is behind for at least one watched consensus
	/// validator. It is possible that the timestamp will be available once the watcher is fully synced.
	TimestampResultCode_WatcherBehind TimestampResultCode = 2
	/// The timestamp cannot be known with the service's current watcher configuration.
	/// In this case, the watcher must be restarted to include in its watched URLs a sufficient
	/// set of consensus validators so that at least one of those validators participated in
	/// consensus for every block.
	TimestampResultCode_Unavailable TimestampResultCode = 3
	/// A WatcherDBError occurred when getting signatures and timestamps.
	TimestampResultCode_WatcherDatabaseError TimestampResultCode = 4
	/// A timestamp was requested for a block index out of bounds, e.g. 0.
	TimestampResultCode_BlockIndexOutOfBounds TimestampResultCode = 5
)

// Enum value maps for TimestampResultCode.
var (
	TimestampResultCode_name = map[int32]string{
		0: "UnusedField",
		1: "TimestampFound",
		2: "WatcherBehind",
		3: "Unavailable",
		4: "WatcherDatabaseError",
		5: "BlockIndexOutOfBounds",
	}
	TimestampResultCode_value = map[string]int32{
		"UnusedField":           0,
		"TimestampFound":        1,
		"WatcherBehind":         2,
		"Unavailable":           3,
		"WatcherDatabaseError":  4,
		"BlockIndexOutOfBounds": 5,
	}
)

func (x TimestampResultCode) Enum() *TimestampResultCode {
	p := new(TimestampResultCode)
	*p = x
	return p
}

func (x TimestampResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimestampResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_watcher_proto_enumTypes[0].Descriptor()
}

func (TimestampResultCode) Type() protoreflect.EnumType {
	return &file_watcher_proto_enumTypes[0]
}

func (x TimestampResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimestampResultCode.Descriptor instead.
func (TimestampResultCode) EnumDescriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{0}
}

var File_watcher_proto protoreflect.FileDescriptor

var file_watcher_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a,
	0x93, 0x01, 0x0a, 0x13, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x75, 0x73, 0x65,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x42, 0x65, 0x68, 0x69, 0x6e, 0x64, 0x10, 0x02, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x03,
	0x12, 0x18, 0x0a, 0x14, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x75, 0x74, 0x4f, 0x66, 0x42, 0x6f, 0x75,
	0x6e, 0x64, 0x73, 0x10, 0x05, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x77, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x3b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_watcher_proto_rawDescOnce sync.Once
	file_watcher_proto_rawDescData = file_watcher_proto_rawDesc
)

func file_watcher_proto_rawDescGZIP() []byte {
	file_watcher_proto_rawDescOnce.Do(func() {
		file_watcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_watcher_proto_rawDescData)
	})
	return file_watcher_proto_rawDescData
}

var file_watcher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_watcher_proto_goTypes = []interface{}{
	(TimestampResultCode)(0), // 0: TimestampResultCode
}
var file_watcher_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_watcher_proto_init() }
func file_watcher_proto_init() {
	if File_watcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watcher_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watcher_proto_goTypes,
		DependencyIndexes: file_watcher_proto_depIdxs,
		EnumInfos:         file_watcher_proto_enumTypes,
	}.Build()
	File_watcher_proto = out.File
	file_watcher_proto_rawDesc = nil
	file_watcher_proto_goTypes = nil
	file_watcher_proto_depIdxs = nil
}
