appname = "xlmDataServer"

[server]
runmode = "debug"
ip="0.0.0.0"
port="18907"
read_timeout= 60
write_timeout= 60

[Sync]
name = "xlm"
enablesync = true
enablegoroutine = true
enablemultiscan=1
enablemempool = false  #
fullbackup = false #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 2
epochtime  = 60
initheight = 39295535
enablerollback = false
rollheight = 10000
confirmations = 6
intervaltime = 20

[nodes.xlm]
#url = "http://54.250.240.45:8000/"
url = "https://horizon.stellar.org/"

#rpc_key = "rylink"
#rpc_secret = "4CpmLnbOiaTbD20gPdsRYY6WiMFDyF8N8QzGGYrAfIw="

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"

[databases.sync]
name= "xlmsync"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"



[push]
enable = true
type = "http" #rabbitmq/http
agent = true
url = "http://127.0.0.1:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="amqp://rylink:rylink2020@172.17.2.65"
reconns=30
publishers=["xlm"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "info" #debug info warn error panic
max_age= 24
rotation_time= 24