appname = "zenDataServer"
mode = "prod"
[server]
runmode = "debug"
ip="0.0.0.0"
port="18908"
read_timeout= 60
write_timeout= 60

[Sync]
name = "zen"
enablesync = true
enablegoroutine = true
enablemempool = true  #
fullbackup = true #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 2
epochtime  = 60
initheight = 841141
enablerollback = false
rollheight = 10000
confirmations = 6
intervaltime = 20

[nodes.zen]
url = "http://rylink:4CpmLnbOiaTbD20gPdsRYY6WiMFDyF8N8QzGGYrAfIw=@zen.rylink.io:30231"


[databases.user]
name= "6kDzq6McR2q5Id4Br0Q="
type= "mysql"
url= "70XjuL0YW323J9ZKolEHy2dO6URED2pJn/zF51B37pivhogejk9cjkpIh6kRh35PEyPR/hrj1l92AFKFiTzy"
user= "70XjuJEOTHmoLdAB"
password= "32in/6k/X2K8fNwO+UIG3Q=="
mode= "release"

[databases.sync]
name= "8UH5qrcTSg=="
type= "mysql"
url= "70bxsqQQRCa9KMYXtVUYn3suNzOh/Z4AvewXK/eJ49f6Ypz+ZsIyjHpyRfL9Z6GNezHXMevAE2/eWAuYvwV+VFIp+AhQo8DORhE5"
user= "70XjuJ0YW323J9Y="
password= "5WDdobo8DWy5fIQ6u25YkoPZ"
mode= "release"



[push]
enable = true
type = "http" #rabbitmq/http
agent = true
url = "http://192.169.2.157:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="6knmqfRSBnmnKNoKqgoC284lriwMppBmnYedYdOK9LFRdab8+F9Fo7uT1PsVaW/XnGhtL5xTqCA="
reconns=30
publishers=["zen"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "info" #debug info warn error panic
max_age= 24
rotation_time= 24
