name = "wtc"
mode = "dev"
[server]
runmode = "debug"
ip="0.0.0.0"
port="15016"
read_timeout= 60
write_timeout= 60

[Sync]
name = "wtc"
enablesync = true
enablegoroutine = false
enablemempool = false  #
fullbackup = false #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 0
epochtime  = 60
initheight = 40300000000
enablerollback = false
rollheight = 180551290000
confirmations = 20
intervaltime = 20
enablemultiscan = 1

address_discover = 10 #新增地址发现:0 不开启, >0 查询间隔秒数
contract_discover = 10 #新增合约发现:0 不开启, >0 查询间隔秒数

[nodes.wtc]
url = "http://13.212.177.203:8765"


[nodes.sol]
#url = "https://solana-api.projectserum.com"
repush = "https://api.mainnet-beta.solana.com"
url = "https://explorer-api.mainnet-beta.solana.com"
#rpc_key = "rylink"
#rpc_secret = "4CpmLnbOiaTbD20gPdsRYY6WiMFDyF8N8QzGGYrAfIw="

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "root"
mode= "release"

[databases.sync]
name= "solsync"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "root"
mode= "release"
[mq]
hostport = "b-30ba08b2-dbea-4e1a-a282-b4569cb9896f.mq.ap-northeast-1.amazonaws.com:5671"
username = "blockchain_coin-MQ"
password  = "draXv3HB4dKqmDjANU"


[push]
enable = false
type = "http" #rabbitmq/http
agent = true
url = "http://192.169.2.157:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="6knmqfRSBnmnKNoKqgoC284lriwMppBmnYedYdOK9LFRdab8+F9Fo7uT1PsVaW/XnGhtL5xTqCA="
reconns=30
publishers=["sol"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug" #debug info warn error panic
max_age= 24
rotation_time= 24
