version: '2'

services:
  substrate:
    container_name: substrate
    image: parity/substrate:3.0.0-dev-1b646b2
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    command: --dev --rpc-external --ws-external --rpc-methods Unsafe --offchain-worker Always
  gsrpc-test:
    image: gsrpc-test
    build: .
    environment:
      - RPC_URL=ws://substrate:9944
      - TEST_PRIV_KEY=//Alice
    volumes:
      - "$PWD:/go-substrate-rpc-client"
