name = "okt"

[server]
runmode = "debug"
ip="0.0.0.0"
port="22004"
read_timeout= 600
write_timeout= 600

[csv]
dir= "csv"
read_file= ""
write_file= ""

[log]
OutFile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24

[node]
url="http://18.176.158.68:32657"
eth2="http://18.176.158.68:26659"
eth="https://exchainrpc.okex.org"
chainid="exchain-66"
fee="0.0005"