name = "wd-wd"

[server]
runmode = "debug"
ip="0.0.0.0"
port="22026"
read_timeout= 60
write_timeout= 60

[csv]
dir= "csv"
read_file= ""
write_file= ""

[log]
OutFile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "debug"
log_path= "tmp"
log_name= "debug.log"
max_age= 24
rotation_time= 24
[node]
#url = "http://13.231.191.20:1234/rpc/v0"
url = "http://54.249.179.242:1234/rpc/v0?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.KiM_OPMD8iQmklTz1HaDTWgACfiQCfT8APc7Ok89Yv0"