name = "tkm"
mode = "prod1"

[Sync]
name = "tkm"
enablesync = true
enablemultiscan = 0
enablegoroutine = false
enablemempool = false
fullbackup = false
epochcount = 100
epochtime  = 60
initheight = 21499955
enablerollback = false
rollheight = 10000
confirmations = 12
intervaltime = 15
address_discover = 10 #新增地址发现:0 不开启, >0 查询间隔秒数
contract_discover = 10 #新增合约发现:0 不开启, >0 查询间隔秒数
#[nodes.eth]
#url = "http://eth.rylink.io:31545"
##url = "http://13.230.253.68:8545"
#rpc_key = ""
#rpc_secret = ""
#
#[nodes.etc]
#url = "http://3.112.208.9:32357"
##url = "http://13.230.253.68:8545"
#rpc_key = ""
#rpc_secret = ""

[nodes.tkm]
#url = "https://public-node.testnet.rsk.co"
url = "http://test1.thinkiumrpc.net"
rpc_key = ""
rpc_secret = ""

#[databases.user]
#name= "6kDzq6McR2q5Id4Br0Q="
#type= "mysql"
#url= "70XjuL0YW323J9ZKolEHy2dO6URED2pJn/zF51B37pivhogejk9cjkpIh6kRh35PEyPR/hrj1l92AFKFiTzy"
#user= "70XjuJEOTHmoLdAB"
#password= "32in/6k/X2K8fNwO+UIG3Q=="
#mode= "release"
#[databases.sync]
#name= "7lD/qrcTSg=="
#type= "mysql"
#url= "70bxsqQQRCW9Jd4eqUEJh6+rxQyAm/u6l7UHpyET8UsjYHSthv5OeRx3jFjl7iccw1ucPR/26dIuNf0="
#user= "70XjuJ0YW323J9Y="
#password= "5WDdobo8DWy5fIQ6u25YkoPZ"
#mode= "release"

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "root"
mode= "release"

[databases.sync]
name= "tkmsync"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "root"
mode= "release"

[server]
runmode = "debug"
ip="0.0.0.0"
port="15020"
read_timeout= 60
write_timeout= 60
[mq]
hostport = "b-30ba08b2-dbea-4e1a-a282-b4569cb9896f.mq.ap-northeast-1.amazonaws.com:5671"
username = "blockchain_coin-MQ"
password  = "draXv3HB4dKqmDjANU"
[push]
enable = true
type = "http"
agent = true
url = "http://192.169.2.157:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="6knmqfRSBnmnKNoKqgoC284lriwMppBmnYedYdOK9LFRdab8+F9Fo7uT1PsVaW/XnGhtL5xTqCA="
reconns=30
publishers=["tkm"]

[log]
level="info"
formatter="json"
outfile="./tmp/debug.out"
errfile="./tmp/debug.err"