name = "domsync"
mode = "dev"

[Sync]
name = "dom"
enablesync = true
enablemultiscan = 0
enablegoroutine = false
enablemempool = false
fullbackup = false
epochcount = 100
epochtime  = 60
initheight = 5753366
enablerollback = false
rollheight = 10000
confirmations = 12
intervaltime = 3

address_discover = 10 #新增地址发现:0 不开启, >0 查询间隔秒数
contract_discover = 10 #新增合约发现:0 不开启, >0 查询间隔秒数

[nodes.dom]
url = "http://192.170.1.9:28803"
#url = "https://smartbch.fountainhead.cash/mainnet"
rpc_key = ""
rpc_secret = ""

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "@AAbb1122"
mode= "release"

[databases.sync]
name= "domsync"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "@AAbb1122"
mode= "release"

[server]
runmode = "debug"
ip="0.0.0.0"
port="15025"
read_timeout= 60
write_timeout= 60

[mq]
hostport = "b-30ba08b2-dbea-4e1a-a282-b4569cb9896f.mq.ap-northeast-1.amazonaws.com:5671"
username = "blockchain_coin-MQ"
password  = "draXv3HB4dKqmDjANU"

[push]
enable = true
type = "http"
agent = true
url = "http://127.0.0.1:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="6knmqfRSBnmnKNoKqgoC284lriwMppBmnYedYdOK9LFRdab8+F9Fo7uT1PsVaW/XnGhtL5xTqCA="
reconns=30
publishers=["dom"]

[log]
level="info"
formatter="json"
outfile="./tmp/debug.out"
errfile="./tmp/debug.err"