appname = "sgbsync"

[server]
runmode = "debug"
ip="0.0.0.0"
port="15005"
read_timeout= 60
write_timeout= 60

[Sync]
name = "sgb-sgb"
enablesync = true
enablemultiscan = 1
enablegoroutine = true
enablemempool = true  #
fullbackup = false #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 2
epochtime  = 60
initheight = 0
enablerollback = false
rollheight = 259096
confirmations = 12
intervaltime = 0
address_discover = 10 #新增地址发现:0 不开启, >0 查询间隔秒数
contract_discover = 10 #新增合约发现:0 不开启, >0 查询间隔秒数
[nodes.sgb-sgb]
url = "http://13.231.191.20:8080"
node = "http://13.231.191.20:9933"

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"

[databases.sync]
name= "sgbsync"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"
[mq]
hostport = "b-30ba08b2-dbea-4e1a-a282-b4569cb9896f.mq.ap-northeast-1.amazonaws.com:5671"
username = "blockchain_coin-MQ"
password  = "draXv3HB4dKqmDjANU"

[push]
enable = false
type = "rabbitmq" #rabbitmq/http
agent = false
url = "http://127.0.0.1:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="amqp://rylink:rylink2020@172.17.2.65"
reconns=30
publishers=["sgb"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"  #text,json
mode= "dev" #dev pro
level= "debug" #debug info warn error panic
