appname = "dotsync"
mode = "prod1"
[server]
runmode = "debug"
ip="0.0.0.0"
port="18876"
read_timeout= 60
write_timeout= 60

[Sync]
name = "dot"
enablesync = true
enablemultiscan = 1
enablegoroutine = true
enablemempool = false  #
fullbackup = false #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 2
epochtime  = 60
initheight = 11395950
enablerollback = false
rollheight = 685988
confirmations = 12
intervaltime = 0

[nodes.dot]
#node="http://192.169.1.153:30993"
node="https://rpc.azero.dev"
scan_api = "https://alephzero.api.subscan.io"
#scan_api = "https://polkadot.api.subscan.io"
scan_key = "494f2c39fa73f17cc38104f7e1cd4841"

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "root"
mode= "release"

[databases.sync]
name= "dotsync"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "root"
mode= "release"


[push]
enable = true
type = "http" #rabbitmq/http
agent = true
url = "http://192.169.2.157:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="6knmqfRSBnmnKNoKqgoC284lriwMppBmnYedYdOK9LFRdab8+F9Fo7uT1PsVaW/XnGhtL5xTqCA="
reconns=30
publishers=["dot"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "json"
mode= "dev" #dev pro
level= "info" #debug info warn error panic
