name = "avaxcchain"

[server]
runmode = "debug"
ip="0.0.0.0"
port="15039"
read_timeout= 60
write_timeout= 60

[Sync]
name = "avaxcchain"
enablesync = false
enablegoroutine = false
enablemultiscan = 1
enablemempool = false  #
fullbackup = true #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 2
epochtime  = 60
initheight = 12381443
enablerollback = false
rollheight = 4623132
confirmations = 11
intervaltime = 12
address_discover = 10 #新增地址发现:0 不开启, >0 查询间隔秒数
contract_discover = 10 #新增合约发现:0 不开启, >0 查询间隔秒数
[nodes.avaxcchain]
url = "https://api.avax.network/ext/bc/C/rpc"

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"

[databases.sync]
name= "avaxcchainsync"
type= "mysql"
url= "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com:3306"
user= "hoocustody"
password= "Eb!ZXrNt!!x5xru0"
mode= "release"
[mq]
hostport = "b-30ba08b2-dbea-4e1a-a282-b4569cb9896f.mq.ap-northeast-1.amazonaws.com:5671"
username = "blockchain_coin-MQ"
password  = "draXv3HB4dKqmDjANU"


[push]
enable = false
type = "http" #rabbitmq/http
agent = false
url = "http://127.0.0.1:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="amqp://rylink:rylink2020@172.17.2.65"
reconns=30
publishers=["avaxcchain"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "info" #debug info warn error panic
max_age= 24
rotation_time= 24