appname = "iota"
mode = "prod1"
[server]
runmode = "debug"
ip="0.0.0.0"
port="15028"
read_timeout= 60
write_timeout= 60

[Sync]
name = "iota"
enablesync = true
enablegoroutine = true
enablemempool = true  #
fullbackup = false #交易全量保存数据库，false 只保存监控地址的交易,arp只能false要更新数据库用户余额
epochcount = 2
epochtime  = 60
initheight = 37679590000
enablerollback = false
rollheight = 10000
confirmations = 6
intervaltime = 20

[nodes.iota]
url = "http://54.250.240.45:15678"
rpc_key = "hoo"
rpc_secret = "123456"

[databases.user]
name= "addrmanagement"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "root"
mode= "release"

[databases.sync]
name= "eacsync"
type= "mysql"
url= "127.0.0.1:3306"
user= "root"
password= "root"
mode= "release"



[push]
enable = true
type = "http" #rabbitmq/http
agent = false
url = "http://192.169.2.157:8090/agent/index"
user = "agentuser"
password = "agentpass"
mqurl="6knmqfRSBnmnKNoKqgoC284lriwMppBmnYedYdOK9LFRdab8+F9Fo7uT1PsVaW/XnGhtL5xTqCA="
reconns=30
publishers=["eac"]

[log]
outfile= "tmplogs/info"
errfile= "tmplogs/err"
formatter= "text"
release= 0.1
mode= "dev"
level= "info" #debug info warn error panic
max_age= 24
rotation_time= 24
