appname = "hecosync"

[Sync]
name = "heco"
enablesync = true
multiscantasknum = 4
multiscannum = 16
initheight = 7664494
enablerollback = false
rollheight = 10000
confirmations = 12
delayheight = 30
sleeptime = 1
enablestop = false
stopheight = 21088845

[nodes.heco]
#url = "47.252.19.181:50051"
url = "https://http-mainnet.hecochain.com"
rpc_key = ""
rpc_secret = ""

[databases.user]
name = "addrmanagement"
type = "mysql"
url = "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com"
user = "hoocustody"
password = "Eb!ZXrNt!!x5xru0"
mode = "release"

[databases.sync]
name = "hecosync"
type = "mysql"
url = "rm-j6c5ekl1af4dc9k8w499.mysql.rds.aliyuncs.com"
user = "hoocustody"
password = "Eb!ZXrNt!!x5xru0"
mode = "release"

[server]
runmode = "debug"
ip = "0.0.0.0"
port = "18080"
read_timeout = 60
write_timeout = 60

[agent]
enable = false
enablepush = true
url = "http://127.0.0.1:8090/agent/index"
user = "test"
password = "test"

[log]
formatter = "text"
release = 0.1
mode = "dev"
level = "trace"
log_path = "tmp"
log_name = "debug.log"
max_age = 24
rotation_time = 24


[mq]
hostport = "b-30ba08b2-dbea-4e1a-a282-b4569cb9896f.mq.ap-northeast-1.amazonaws.com:5671"
username = "blockchain_coin-MQ"
password  = "draXv3HB4dKqmDjANU"


[push]
enable = true
type = "http"
agent = true
url = "http://127.0.0.1:8090/agent/index"
user = "test"
password = "test"
mqurl = "amqp://guest:guest@localhost:5672/"
